

USE ComexDB;
GO

SELECT
	SUM(f.VL_FRETE) AS FreteUSD,
	SUM(f.VL_SEGURO) AS SeguroUSD,
	CAST(SUM(CASE WHEN f.TIPO_MOVIMENTO = 'Importação' THEN VL_FRETE ELSE 0 END) + SUM(CASE WHEN f.TIPO_MOVIMENTO = 'Importação' THEN VL_SEGURO ELSE 0 END) AS DECIMAL(38,2))
	/
	NULLIF(SUM(CASE WHEN f.TIPO_MOVIMENTO = 'Importação' THEN VL_FOB ELSE 0 END), 0) AS OverheadLogisticoPercentual
FROM
	fMovimentacoes AS f