USE ComexDB;
GO


----------------------------------------------------
-- Tabela Fato: fMovimentacoes
----------------------------------------------------

CREATE TABLE fMovimentacoes (
	FK_DATA DATE,
	FK_PRODUTO VARCHAR(8),
	FK_PAIS VARCHAR(5),
	FK_UNIDADE VARCHAR(255),
	FK_VIA VARCHAR(255),
	FK_URF VARCHAR(255),
	TIPO_MOVIMENTO VARCHAR(20),
	QT_ESTAT BIGINT,
	KG_LIQUIDO BIGINT,
	VL_FOB BIGINT,
	VL_FRETE BIGINT,
	VL_SEGURO BIGINT,
	VL_CIF BIGINT
);
GO

-- Inserindo os dados de EXPORTAÇÃO
INSERT INTO fMovimentacoes (
	FK_DATA, FK_PRODUTO, FK_PAIS, FK_UNIDADE, FK_VIA, FK_URF, 
	TIPO_MOVIMENTO, QT_ESTAT, KG_LIQUIDO, VL_FOB
)
SELECT
	DATEFROMPARTS(exp.CO_ANO, exp.CO_MES, 1) AS FK_DATA,
	exp.CO_NCM AS FK_PRODUTO,
	exp.CO_PAIS AS FK_PAIS,
	exp.CO_UNID AS FK_UNIDADE,
	exp.CO_VIA AS FK_VIA,
    exp.CO_URF AS FK_URF,
    'Exportação' AS TIPO_MOVIMENTO,
	CAST(exp.QT_ESTAT AS BIGINT) AS QT_ESTAT,
	CAST(exp.KG_LIQUIDO AS BIGINT) AS KG_LIQUIDO,
	CAST(exp.VL_FOB AS BIGINT) AS VL_FOB
FROM stage_exp_completa AS exp;
GO

-- Inserindo os dados de IMPORTAÇÃO
INSERT INTO fMovimentacoes (
	FK_DATA, FK_PRODUTO, FK_PAIS, FK_UNIDADE, FK_VIA, FK_URF, 
	TIPO_MOVIMENTO, QT_ESTAT, KG_LIQUIDO, VL_FOB, VL_FRETE, VL_SEGURO, VL_CIF
)
SELECT
    DATEFROMPARTS(imp.CO_ANO, imp.CO_MES, 1) AS FK_DATA,
    imp.CO_NCM AS FK_PRODUTO,
    imp.CO_PAIS AS FK_PAIS,
    imp.CO_UNID AS FK_UNIDADE,
    imp.CO_VIA AS FK_VIA,
    imp.CO_URF AS FK_URF,
    'Importação' AS TIPO_MOVIMENTO,
    CAST(imp.QT_ESTAT AS BIGINT) AS QT_ESTAT,
    CAST(imp.KG_LIQUIDO AS BIGINT) AS KG_LIQUIDO,
    CAST(imp.VL_FOB AS BIGINT) AS VL_FOB,
    CAST(imp.VL_FRETE AS BIGINT) AS VL_FRETE,
    CAST(imp.VL_SEGURO AS BIGINT) AS VL_SEGURO,
	CAST(imp.VL_FOB AS BIGINT) + CAST(imp.VL_FRETE AS BIGINT) + CAST(imp.VL_SEGURO AS BIGINT) AS VL_CIF
FROM
    stage_imp_completa AS imp;
GO