USE ComexDB;
GO

SELECT
	CO_ANO,
	COUNT(*) AS NUMERO_LINHAS,
	SUM(CAST(VL_FOB AS BIGINT)) AS VL_FOB,
	SUM(CAST(KG_LIQUIDO AS BIGINT)) AS KG_LIQUIDO,
	SUM(CAST(QT_ESTAT AS BIGINT)) AS QT_ESTAT
FROM
	stage_exp_completa
WHERE
	CO_ANO IN (2022, 2023, 2024, 2025)
GROUP BY
	CO_ANO
ORDER BY
	CO_ANO;